### ISSUE TITLE
local install

### ISSUE THREAD

**Issue by enuggetry** [sakshamsaxena/sails-hook-jbvcs#18]
I cloned it in my sails app's node_modules dir:

`git clone https://github.com/sakshamsaxena/sails-hook-jbvcs.git
`
I initially tried to install as a local module without -g option but it failed.

`npm install sails-hook-jbvcs
`

With the -g option, it seems to install fine.

**Comment by sakshamsaxena** [comment]
After cloning, you change into the cloned directory and then simply ```npm install``` to install from the package.json in that directory. 
Either way, I'll push the latest version to npm registry so that you can install it using ```npm install sails-hook-jbvcs```
On 19-Aug-2016 8:01 AM, Eric Y <notifications@github.com> wrote:I cloned it in my sails app's node_modules dir:

git clone https://github.com/sakshamsaxena/sails-hook-jbvcs.git

I initially tried to install as a local module without -g option but it failed.

npm install sails-hook-jbvcs


With the -g option, it seems to install fine.

**Comment by sakshamsaxena** [comment]
v0.2.0 is the latest tagged version. Pushed it to npm registry as well, but if you're cloning already, then simply ``` npm install```. Preferably link sails before this. Totally upto you how you use it.
