### ISSUE TITLE
Version directories specifications

### ISSUE THREAD

**Issue by enuggetry** [sakshamsaxena/sails-hook-jbvcs#21]
In the command, is there a way to specify where the version directories will be created?  Or, does it just create the directories in the location where you run it from?

`sudo jbvcs -u enuggetry -r jbvcs-test -w 1000 0`

It might be a good idea to have an option to specify the target directory, like: -d /mydir

**Comment by sakshamsaxena** [comment]
The CLI doesn't come with any new features. It's basically an interface which calls the defined functions of the module. Because the directory is hard coded for now within the module, there's no scope of adding a directory parameter.
On 22-Aug-2016 11:05 AM, Eric Y <notifications@github.com> wrote:In the command, is there a way to specify where the version directories will be created?  Or, does it just create the directories in the location where you run it from?

sudo jbvcs -u enuggetry -r jbvcs-test -w 1000 0

It might be a good idea to have an option to specify the target directory, like: -d /mydir

**Comment by enuggetry** [comment]
The lack of ability to specify the target dir is rather limiting.
